name: Run build

on:
  workflow_dispatch: # Allow manual triggers
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tensorflow:
    name: Build TensorFlow
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tf-version: [2.12, 2.13, 2.14, 2.15]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install jupyterlab ipython==7.34.0 tensorflow==${{ matrix.tf-version }}
          pip install dist/edge_mdt_nightly-0.0.0.dev0-py3-none-any.whl['tf']

      - name: pip list
        run: |
          pip list

      - name: run notebook
        working-directory: tutorials
        run: |
          jupyter nbconvert --to notebook --execute keras_mobilenetv2.ipynb --output keras_mobilenetv2_output.ipynb
          
      - name: upload output
        uses: actions/upload-artifact@v4
        with:
          name: tf-${{ matrix.tf-version }}
          if-no-files-found: error
          retention-days: 1
          path: |
            ./tutorials/keras_mobilenetv2_output.ipynb
            ./tutorials/mobilenet_tf/packerOut.zip



  tests-pytorch:
    name: Build PyTorch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pt-version: [ '2.0', 2.1, 2.2, 2.3, 2.4, 2.5, 2.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: build and install
        run : |
          python -m pip install --upgrade pip
          ./build.sh
          pip install jupyterlab torch==${{ matrix.pt-version }}
          pip install dist/edge_mdt_nightly-0.0.0.dev0-py3-none-any.whl['pt']

      - name: pip list
        run: |
          pip list

      - name: run notebook
        working-directory: tutorials
        run: |
          jupyter nbconvert --to notebook --execute pytorch_mobilenetv2.ipynb --output pytorch_mobilenetv2.ipynb

      - name: upload output
        uses: actions/upload-artifact@v4
        with:
          name: pt-${{ matrix.pt-version }}
          if-no-files-found: error
          retention-days: 1
          path: |
            ./tutorials/pytorch_mobilenetv2.ipynb
            ./tutorials/mobilenet_pt/packerOut.zip
